<div class="flex column">
<?php if ($cart_items): ?>
    <div class="box header">
        <div>Carrinho de compras</div>
    </div>
    <?php foreach ($cart_items as $item): ?>
    <div class="box flex align-center space-between cart">
        <div class="flex align-center space-between">
            <div><img alt="" src="/images/<?= $item['image'] ?>.png" /></div>
            <div>
                <div><?= $item['full_name_br'] ?></div>
                <div class="en"><?= $item['full_name'] ?></div>
            </div>
        </div>
        <div class="flex align-center space-between">
            <div class="delete">
                <a href="/cart/delete?item_id=<?= $item['id'] ?>">
                    <img alt="" src="/styles/delete_icon.png" />
                </a>
            </div>
            <div class="price">
            <?php if ($item['offer_price'] ?? false): ?>
                <div class="line_through"><?= html_money($item['price']) ?></div>    
                <div><?= html_money($item['offer_price']) ?></div>
            <?php else: ?>
                <div><?= html_money($item['price']) ?></div>
            <?php endif ?>
            </div>
        </div>
    </div>
    <?php endforeach ?>
    <?php if ($message ?? false): ?>
        <div class="box notification">
            <?= $message ?>
        </div>
    <?php elseif ($message_failure ?? false): ?>
        <div class="box notification failure">
            <?= $message_failure ?>
        </div>
    <?php endif ?>
    <div class="box flex column">
        <form action="/cart/coupon" method="post">
            <label for="cupom">Cupom</label>
            <div class="flex align-center space-between">
                <input id="cupom" name="coupon" type="text" value="<?= $coupon_name ?? '' ?>" />
                <button type="submit">Adicionar</button>
            </div>
        </form>
    </div>
    <div class="box white">
        <div class="flex align-center space-between">
            <div>Subtotal</div>
            <div><?= html_money($subtotal) ?></div>
        </div>
        <div class="flex align-center space-between">
            <div>Desconto</div>
            <div>(<?= $percent ?>%) <?= html_money($discount) ?></div>
        </div>
        <div class="flex align-center space-between">
            <div>Total</div>
            <div><?= html_money($total) ?></div>
        </div>
    </div>
    <div id="nav_buttons">
        <a href="/">Continuar comprando</a>
        <a href="/checkout">Continuar para o pagamento</a>
    </div>
<?php else: ?>
    <div class="box header">
        <div>O seu carrinho está vazio.</div>
    </div>
    <div id="nav_buttons">
        <a href="/">Continuar comprando</a>
    </div>
<?php endif ?>
</div>