<nav>
    <div nav id="nav_weapon">
        <a href="?item=weapon:AK-47">AK-47</a>
        <a href="?item=weapon:AUG">AUG</a>
        <a href="?item=weapon:AWP">AWP</a>
        <a href="?item=weapon:Sawed-Off">Cano Curto</a>
        <a href="?item=weapon:Desert Eagle">Desert Eagle</a>
        <a href="?item=weapon:FAMAS">FAMAS</a>
        <a href="?item=weapon:Five-SeveN">Five-SeveN</a>
        <a href="?item=weapon:Galil AR">Galil AR</a>
        <a href="?item=weapon:Glock-18">Glock-18</a>
        <a href="?item=weapon:MAC-10">MAC-10</a>
        <a href="?item=weapon:M4A1-S">M4A1-S</a>
        <a href="?item=weapon:M4A4">M4A4</a>
        <a href="?item=weapon:Nova">Nova</a>
        <a href="?item=weapon:P90">P90</a>
        <a href="?item=weapon:R8 Revolver">Revolvér R8</a>
        <a href="?item=weapon:SG 553">SG 553</a>
        <a href="?item=weapon:SSG 08">SSG 08</a>
        <a href="?item=weapon:USP-S">USP-S</a>
        <a href="?item=weapon:XM1014">XM1014</a>
        <a href="?item=agent">Agentes</a>
    </div>
    <!--
    <div class="banner">
        <a href="https://twitch.tv/dgobode" target="_blank">
            <picture>
                <source media="(min-width: 769px)" srcset="/s/sorteio_dgobode_1200w.webp" type="image/webp" />
                <source media="(min-width: 769px)" srcset="/s/sorteio_dgobode_1200w.png" type="image/png" />
                <source media="(max-width: 768px)" srcset="/s/sorteio_dgobode_600w.webp" type="image/webp" />
                <source media="(max-width: 768px)" srcset="/s/sorteio_dgobode_600w.png" type="image/png" />
                <img alt="Sorteio Canal do bode" src="/s/sorteio_dgobode_1200w.png" />
            </picture>
        </a>
    </div>
    -->
    <div id="nav_order">
        <a class="order" data-order="asc" href="">Menor preço</a>
        <a class="order" data-order="desc" href="">Maior preço</a>
    </div>
</nav>
<div hidden="hidden" id="expanded">
    <div class="image">
        <img alt="" src="/styles/loading.svg" />
    </div>
</div>
<div id="container"></div>
<template>
    <div class="item">
        <div class="title">
            <div>
                <span class="weapon"></span>
                <span class="stattrak"></span>
            </div>            
            <div class="name"></div>
        </div>
        <div class="image" data-name="">
            <a href="">
                <img alt="" src="/styles/loading.svg" />
            </a>
        </div>
        <div class="exterior tag"></div>
        <div class="market">
            <a href="" target="_blank">Mercado Steam</a>
        </div>
        <div class="availability tag">Sob encomenda</div>
        <div>
            <a class="button_buy" href="">Comprar</a>
        </div>
        <div class="buy">
            <div class="old_price"></div>
            <div class="price"></div>
        </div>
    </div>
</template>
<script src="/scripts/default.js"></script>