<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta property="og:image" content="https://undeadstore.com.br/logo.png" />
<meta property="og:description" content="Skins de Counter-Strike 2 com os melhores preços." />
<meta property="og:title" content="Undead Store" />
<link href="/favicon.png" rel="icon" type="image/x-icon" />
<link href="/styles/layout.css" rel="stylesheet" />
<link href="/styles/default.css" rel="stylesheet" />
<link href="/styles/index.css" rel="stylesheet" />
<link href="/styles/mobile.css" rel="stylesheet" />
<title><?= isset($settings_title) ? "{$settings_title} | Undead Store" : 'Undead Store' ?></title>
</head>
<body>

<div id="grid">
    <header id="main_header">
        <div class="left">
            <a href="/">
                <img alt="Logotipo" src="/styles/logo128.png" />
            </a>
        </div>
        <nav class="right">
            <div class="cart_button">
                <a class="image" href="/cart">
                    <img alt="Imagem de um carrinho" src="/styles/cart_icon.png" />
                </a>
            </div>
            <?php if ($session->get('logged_in')): ?>
                <div id="loggedin">
                    <div class="steam image">
                        <img alt="Avatar" src="<?= $session->get('steam_avatar') ?>" />
                        <span><?= $session->get('steam_name') ?></span>
                    </div>
                </div>
            <?php else: ?>
                <div id="login">
                    <a class="image" href="/auth">
                        <span>Entrar</span>
                        <img alt="Steam logo" src="/styles/logo_steam.svg" />
                    </a>
                </div>
            <?php endif ?>
            <?php if ($session->get('logged_in')): ?>
                <nav>
                    <a href="/settings">Configurações</a>
                    <a href="/orders">Pedidos</a>
                    <a href="/logout">Sair</a>
                </nav>
            <?php endif ?>
        </nav>
    </header>
    <section>
        <?php require $content_view; ?>
    </section>
    <footer>
        <div class="flex_space_between">
            <div>
                <div>Links</div>
                <a href="/partners">Parceiros</a>
            </div>
            <div class="flex column">
                <div>Formas de pagamento</div>
                <div class="flex icons">
                    <div>
                        <img alt="Logo do Pix" src="/styles/pix_icon.png" />
                    </div>
                    <div>
                        <img alt="Logo do Mercado Pago" src="/styles/mercadopago_icon.png" />
                    </div>
                </div>
            </div>
            <div class="flex column">
                <div>Certificados</div>
                <div class="flex icons">
                    <a href="https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fundeadstore.com.br&hl=pt_BR" target="_blank">
                        <img alt="Logo do Google Safe Browsing" src="/styles/safe_browsing_icon.png" />
                    </a>
                </div>
            </div>
            <div class="flex column">
                <div>Redes sociais</div>
                <div class="social">
                    <a href="https://discord.gg/YMvX8g5FhU">
                        <img alt="Discord logo" src="/styles/discord_icon.svg" />
                    </a>
                    <a href="https://steamcommunity.com/groups/undeadstore">
                        <img alt="Steam logo" src="/styles/steam_icon.svg" />
                    </a>
                </div>
            </div>
        </div>
        <div>Undead Store 2024</div>
        <div>Não somos afiliados a Valve.</div>
    </footer>
</div>
    
</body>
</html>