<div class="flex_column">
    <div class="box">
        <a href="https://www.twitch.tv/dgobode" target="_blank">dgobode - Twitch</a>
        <a href="https://www.twitch.tv/dgobode" target="_blank">
            <img src="https://static-cdn.jtvnw.net/jtv_user_pictures/7d4120ad-8b73-42e9-87f9-83e42c403f03-profile_image-300x300.png" />
        </a>
    </div>
    <div class="box">
        <a href="https://www.youtube.com/@dgobode" target="_blank">dgobode - YouTube</a>
        <a href="https://www.youtube.com/@dgobode" target="_blank">
            <img src="https://static-cdn.jtvnw.net/jtv_user_pictures/7d4120ad-8b73-42e9-87f9-83e42c403f03-profile_image-300x300.png" />
        </a>
    </div>
</div>