<div id="pay">
    <div class="qrcode">
        <div>Use o QR Code para pagar</div>
        <div class="image">
            <img alt="QRCode para pagamento" src="/qrcode?data=<?= $code ?>" />
        </div>
        <div class="total">R$ <?= number_format($total, 2, ',', '.') ?></div>
        <button class="clipboard" data-clipboard="<?= $code ?>">Copiar código</button>
    </div>
</div>
<script>
document.querySelector('.clipboard').addEventListener('click', (e) =>
{
    navigator.clipboard.writeText(e.target.dataset.clipboard);
});
</script>