<div class="flex column">
    <div class="box">
        <form action="" method="post">
            <div class="flex column gap-20">
                <div>
                    <label for="subject">Assunto</label>
                    <input id="subject" name="subject" type="text" />
                </div>
                <div>
                    <label for="subject">Mensagem</label>
                    <textarea id="message" name="message" rows="6"></textarea>
                </div>
                <div>
                    <button type="submit">Enviar</button>
                </div>
            </div>
        </form>
    </div>
</div>